---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: docker-cleanup
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app: docker-cleanup
    spec:
      volumes:
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
      containers:
      - name: docker-cleanup
        image: ocanema/docker-cleanup
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
